package com.nab.entities;
// Generated Aug 23, 2018 10:38:45 AM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Authorizations generated by hbm2java
 */
@Entity
@Table(name = "AUTHORIZATIONS", schema = "dbo", catalog = "CauLacBo")
public class Authorizations implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer AId;
	private Integer RId;
	private String url;

	public Authorizations() {
	}

	public Authorizations(Integer RId, String url) {
		this.RId = RId;
		this.url = url;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "a_id", unique = true, nullable = false)
	public Integer getAId() {
		return this.AId;
	}

	public void setAId(Integer AId) {
		this.AId = AId;
	}

	@Column(name = "r_id")
	public Integer getRId() {
		return this.RId;
	}

	public void setRId(Integer RId) {
		this.RId = RId;
	}

	@Column(name = "url", length = 100)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

}
