package com.nab.entities;
// Generated Aug 23, 2018 10:38:45 AM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.AssociationOverride;
import javax.persistence.AssociationOverrides;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsersRoles generated by hbm2java
 */
@Entity
@Table(name = "USERS_ROLES", schema = "dbo", catalog = "CauLacBo")
public class UsersRoles implements java.io.Serializable {
//	@AssociationOverrides({ 
//		@AssociationOverride(name = "FK_u_id", joinColumns = @JoinColumn(name = "u_id")),
//		@AssociationOverride(name = "FK_r_id", joinColumns = @JoinColumn(name = "r_id")) })
	private static final long serialVersionUID = 1L;
	private Integer urId;
	private Role role;
	private User users;

	public UsersRoles() {
	}

	public UsersRoles(Role role, User users) {
		this.role = role;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ur_id", unique = true, nullable = false)
	public Integer getUrId() {
		return this.urId;
	}

	public void setUrId(Integer urId) {
		this.urId = urId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "r_id")
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "u_id")
	public User getUsers() {
		return this.users;
	}

	public void setUsers(User users) {
		this.users = users;
	}

}
