package com.nab.entities;
// Generated Aug 13, 2018 4:31:45 PM by Hibernate Tools 5.2.11.Final

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Finance generated by hbm2java
 */
@Entity
@Table(name = "FINANCE", schema = "dbo", catalog = "CauLacBo")
public class Finance implements java.io.Serializable {

	private Long fid;
	private Serializable description;
	private Long pid;
	private BigDecimal money;
	private String ftype;

	public Finance() {
	}

	public Finance(Serializable description, Long pid, BigDecimal money, String ftype) {
		this.description = description;
		this.pid = pid;
		this.money = money;
		this.ftype = ftype;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "fid", unique = true, nullable = false)
	public Long getFid() {
		return this.fid;
	}

	public void setFid(Long fid) {
		this.fid = fid;
	}

	@Column(name = "description")
	public Serializable getDescription() {
		return this.description;
	}

	public void setDescription(Serializable description) {
		this.description = description;
	}

	@Column(name = "pid")
	public Long getPid() {
		return this.pid;
	}

	public void setPid(Long pid) {
		this.pid = pid;
	}

	@Column(name = "money", scale = 4)
	public BigDecimal getMoney() {
		return this.money;
	}

	public void setMoney(BigDecimal money) {
		this.money = money;
	}

	@Column(name = "ftype", length = 100)
	public String getFtype() {
		return this.ftype;
	}

	public void setFtype(String ftype) {
		this.ftype = ftype;
	}

}
