package com.nab.entities;
// Generated Aug 13, 2018 4:31:45 PM by Hibernate Tools 5.2.11.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name = "PERSON", schema = "dbo", catalog = "CauLacBo")
public class Person implements java.io.Serializable {

	private Long pid;
	private Serializable pname;
	private Integer age;
	private String sex;
	private String typecode;
	private String avatar;

	public Person() {
	}

	public Person(Serializable pname, Integer age, String sex, String typecode, String avatar) {
		this.pname = pname;
		this.age = age;
		this.sex = sex;
		this.typecode = typecode;
		this.avatar = avatar;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "pid", unique = true, nullable = false)
	public Long getPid() {
		return this.pid;
	}

	public void setPid(Long pid) {
		this.pid = pid;
	}

	@Column(name = "pname")
	public Serializable getPname() {
		return this.pname;
	}

	public void setPname(Serializable pname) {
		this.pname = pname;
	}

	@Column(name = "age")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Column(name = "sex", length = 25)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "typecode", length = 10)
	public String getTypecode() {
		return this.typecode;
	}

	public void setTypecode(String typecode) {
		this.typecode = typecode;
	}

	@Column(name = "avatar")
	public String getAvatar() {
		return this.avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

}
